[package]
name = "deployer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
reqwest = "0.12.7"
serde = "1.0.209"
serde_derive = "1.0.209"
serde_json = "1.0.127"
